import os, base64, smtplib, config
from cryptography.fernet import Fernet
from tkinter import *

class noobCry:
    def __init__(self,fileName, key, location, encryptedFile,f):#initialize all of the variables in the Class
        self.fileName = fileName
        self.fernetKey = fernetKey
        self.encryptedFile = encryptedFile
        self.fernetObject = fernetObject
    #End __init__

    def encrypt(fileName,location):
        for root, dirs, files in os.walk(location, topdown=True):#This loop iterates over directories passed as the first argument, the second arg iterates from the top of directory
            if fileName in files:#If the file is found, it triggers the encryption here
                fernetKey = Fernet.generate_key()#create key
                fernetObject = Fernet(fernetKey)#create object to use the key
                with open(fileName, "rb") as file:#open the file, using the "read bytes" built-in function
                    fileData = file.read()#read the data into fileData variable
                    encryptedFile = fernetObject.encrypt(fileData)#take the f object containing the key and use is the encrypt the target data
                    with open(fileName, "wb") as file:#open the file again using the "write bytes" built in function
                        file.write(encryptedFile)#write the encypted data to the file
                        return fernetKey
    #End encrypt()

    def email(email,password,fernetKey):
        server = smtplib.SMTP('smtp.gmail.com:587')
        server.ehlo()
        server.starttls()
        subject = "autogenerated email"
        message = 'Subject: {}\n\n{}'.format(subject, fernetKey)
        server.login(email,password)
        server.sendmail(email,password,message)
        server.quit()
    #End email



#Gui Setup
window = Tk()# Tk object I think
window.title("noobCry")#Window Label
window.geometry('420x140')#Blaze it

#name label
labelName = Label(window, text="File name:")
labelName.grid(column=0, row=0)

#name input
textName = Entry(window,width=50)
textName.grid(column=1, row=0)

#email labels
labelEmail = Label(window, text="Email:")
labelEmail.grid(column=0,row=6)

#email input
textEmail = Entry(window, width=50)
textEmail.grid(column=1, row=6)

#password label
labelPassword = Label(window, text="Password:")
labelPassword.grid(column=0, row=7)

#password input
textPassword = Entry(window,width=50)
textPassword.grid(column=1, row=7)
textPassword.config(show = "*")

#Location label
labelLocation = Label(window, text="Enter file location:")
labelLocation.grid(column=0, row=1)

#Location input
textLocation = Entry(window,width=50)
textLocation.grid(column=1, row=1)
textInTextLocation = Text(textLocation, width=40, height=10)
textInTextLocation.insert('1.0','Enter file location')


#on 'Confirm' button click, gets text from the fields and feeds them into 
def confirm():
    #hold the file name
    fileName = textName.get()
    #hold the directory location
    location = textLocation.get()
    #hold the email address
    email = textEmail.get()
    #hold the password
    password = textPassword.get()
    #hold the fernet key, received after calling encrypt()
    fernetKey = noobCry.encrypt(fileName,location)
    #
    noobCry.email(email,password,fernetKey)
    labelLocation = Label(window, text="Encypted!\nEmail sent.")
    labelLocation.grid(column=0, row=7)
def close():
    exit()
#End confirm()
#This code sets up the buttons
buttonEncrypt = Button(window, text="Encrypt and send E-mail", command=confirm)
buttonEncrypt.grid(column=1, row=8)
buttonClose = Button(window, text=" Close ", command=close)
buttonClose.grid(column=1, row=9)
#this is the loop that keeps the window open
window.mainloop()